// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID        string  `json:"id"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Bio       *string `json:"bio"`
}

type NewStory struct {
	StoryTitle string `json:"storyTitle"`
	StoryBody  string `json:"storyBody"`
}

type Story struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}
